# Generated by Django 4.1.1 on 2022-09-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='shaba',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
