# Generated by Django 4.1.1 on 2022-09-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_transaction_shaba'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='count',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.BooleanField(blank=True, default='null', null=True),
        ),
    ]
