# Generated by Django 4.1.1 on 2022-10-02 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_otpcode_alter_product_off'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='off',
        ),
    ]
